version: '3'

services:
  bot:
    build: .
    networks:
      - all

  mysql:
    image: mysql:8.0.17
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "guest"
      MYSQL_DATABASE: clothes
    volumes:
      - './db/:/docker-entrypoint-initdb.d/'
    networks:
      - all

#  rabbitmq:
#    image: 'rabbitmq'
#    ports:
#      - '5672:5672'
#    networks:
#      - all

networks:
  all:
